version: '3'
 
services:
 
    php:
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./app:/var/www/html/laravel_crud
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - mysql
 
    nginx:
        image: nginx:1.13.8
        ports:
            - 8081:80
        volumes:
            - ./app:/var/www/html/laravel_crud
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - php
 
    mysql:
        image: mysql:5.7
        container_name: laravel_crud_mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}